# local config
# use with : jekyll build --config _config.yml,_config_dev.yml
baseurl: "/jekyll/JekyllDoc/_site/"
url: "http://test.dev"

googleAnalyticsCode: NOCODE

sass:
  style: :nested







# testing github pages variables
# see https://help.github.com/articles/repository-metadata-on-github-pages
# this hash is only available in dev env
github:
    versions:
        jekyll: 1.5.1
        kramdown: 1.3.1
        liquid: 2.5.5
        maruku: 0.7.0
        rdiscount: 2.1.7
        redcarpet: 2.3.0
        RedCloth: 4.2.9
        jemoji: 0.1.0
        jekyll-mentions: 0.0.6
        jekyll-redirect-from: 0.3.1
        jekyll-sitemap: 0.2.0
        github-pages: 18
        ruby: 2.1.1




