# local config
# use with : jekyll build --config _config.yml,_config_dev.yml
baseurl: "/jekyll/doc/_site"
url: "http://test.dev"

googleAnalyticsCode: NOCODE

sass:
  style: :nested

  cache: false # not working
  read_cache: false # not working

  css_location: css # not working
