# Site settings
title: Jeckyll documentation and testbed
email: david.jacquel@gmail.com

description: "This is my personal Jekyll documentation."

baseurl: "/JekyllDoc"
url: "http://pygmeeweb.com"

twitter_username: pygmeeweb
github_username:  djacquel

# Build settings
markdown: kramdown
permalink: pretty
