# Site settings
title: Jeckyll documentation and testbed
email: david.jacquel@gmail.com

description: "This is my personal Jekyll documentation and testbed."

baseurl: "/JekyllDoc"
url: "http://pygmeeweb.com"

twitter_username: pygmeeweb
github_username:  djacquel

# Build settings
markdown: kramdown
permalink: pretty


sass:
  sass_dir: assets/stylesheets

googleAnalyticsCode: UA-157621-1

# packages versions

twb-sass-version: 2.3.0
