# Site settings
title: Jeckyll testbed
email: david.jacquel@gmail.com

description: "This is my personal Jekyll testbed."

baseurl: "/JekyllDoc"
url: "http://pygmeeweb.com"

twitter_username: pygmeeweb
github_username:  djacquel

# Build settings
markdown: kramdown
permalink: pretty

kramdown:
  input: GFM

sass:
  sass_dir: assets/stylesheets

googleAnalyticsCode: UA-157621-1

# packages versions

twb-sass-version: 2.3.0

exclude:
  - assets/stylesheets/variables.scss
  - assets/stylesheets/bootstrap
  - readme.md

include: []
